server:
  port: 9010

spring:
  application:
    name: oarth-resource
    version: ${project.version}
  profiles:
    active: ${profile.active}

security:
  oauth2:
    client:
      client-id: resource_server
      client-secret: resource
    resource:
      user-info-uri: http://localhost:9024/uaa/user/current
      jwt:
        key-uri: http://localhost:9024/uaa/oauth/token_key