server:
  port: 8085

spring:
  application:
    name: oauth-client-sso
    version: ${project.version}
  profiles:
    active: ${profile.active}

security:
  oauth2:
    client:
      client-id: client_sso
      client-secret: client
      user-authorization-uri: http://localhost:9024/uaa/oauth/authorize
      access-token-uri: http://localhost:9024/uaa/oauth/token
    sso:
      login-path: http://localhost:9024/uaa/login

