server:
  port: 9024
  servlet:
    context-path: /uaa

spring:
  application:
    name: ${project.name}
    version: ${project.version}
  profiles:
    active: ${profile.active}

jwt:
  signing:
    key: smilly