server:
  port: @application.port@
  servlet:
    context-path: ${context.path}

spring:
  application:
    name: ${application.name}
    version: ${project.version}
  profiles:
    active: ${profile.active}

security:
  oauth2:
    client:
      client-id: ${client.id}
      client-secret: ${client.secret}
      user-authorization-uri: http://localhost:9024/uaa/oauth/authorize
      access-token-uri: http://localhost:9024/uaa/oauth/token
      grant-type: ${client.grant.type}
    resource:
      user-info-uri: http://localhost:9024/uaa/user
      jwt:
        key-uri: http://localhost:9024/uaa/oauth/token_key
    sso:
      login-path: http://localhost:9024/uaa/login
